name: Publish Domserver
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Domserver
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: rmartinsanta/domserver
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: domjudge-template/domserver
